### PR TITLE
Set resource requests and limits for all containers

### PR DESCRIPTION
**Pull request by Arau**
Resource requests and limits for:
- scheduler
- csi attacher
- csi provisioner
- csi resizer

(api-manager has merged to api-manager)

I only modified the containers that are deployed in production. The thresholds
are based on real monitoring numbers. Hence only the containers with
production releases have been taken into consideration.

The resources are hardcoded, even though it is agreed that the
parameters ought to be defined in the StorageOSCluster CR eventually.

I made changes on the latest version of the deployments and develop where I found it in the channels dir. Let me know if that change should be put in place somewhere else. I apologise if it is the wrong place.
The PR is risen for review and if the manifests are modified in the right place, I'll proceed with a testing cluster to deploy the containers with the resources set building the operator locally. 

To gather the information about the statistics we deployed a cluster and provision+attached 100s of volumes both RWO and RWX to have an idea of the resource consumption. 
Screen Shot 2022-01-15 at 10 13 10
Screen Shot 2022-01-15 at 10 12 25
Screen Shot 2022-01-15 at 10 12 17
Screen Shot 2022-01-15 at 10 12 09
Screen Shot 2022-01-15 at 10 11 52
Screen Shot 2022-01-15 at 10 11 43

### CODE REVIEW

**Comment by mhmxs** [comment]
Thanks a lot @Arau,

Could you please revert the api-manager change, because it has to file in api manager repository.
Do you have numbers for operator itself?

**Comment by Arau** [comment]
> Thanks a lot @Arau,
> 
> Could you please revert the api-manager change, because it has to file in api manager repository. Do you have numbers for operator itself?

Thank you for the info! I reverted the change for the api-manager and looking into the different repo. I'm attaching the info for the operator container. 

Screen Shot 2022-01-17 at 09 39 53

I believe something like the following would work for the operator. Where is it that this need to be set? 
```
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 5m
            memory: 80Mi
```

**Review by mhmxs — APPROVED** [review]

**Comment by Arau** [comment]
Thank you for the review. I'll build the whole project and run it internally to make sure all the requests and limits make sense before merging. 
I want to make sure I didn't make a mistake with the units shown in the metrics.

**Review by mhmxs — APPROVED** [review]

**Comment by Arau** [comment]
@mhmxs @nolancon I checked with a build of the operator that the units for the requests and limits are correct. Is there anything that needs to be done before merging?

**Comment by mhmxs** [comment]
@Arau If you feel you are done, please press "ready for review" button.

**Pull request merged**
