### PR TITLE
Remove clutter from makefile

### PR DESCRIPTION
**Pull request by Ricardo-Osorio**
Remove methods/etc that seem old/outdated (5months+ since last catalog image push)
Remove setting gobin path and env vars that have no apparent use

### CODE REVIEW

**Comment by mhmxs** [comment]
Hey, fyi, make controller-gen is a standard kubebuilder target.

**Comment by Ricardo-Osorio** [comment]
I am looking at operatorhub for reference and I see some with it and some without. What would you say its the purpose/usefulness of having it? Or where can I read more about it?

**Comment by mhmxs** [comment]
@Ricardo-Osorio Personally i like to download the project's dependencies without copying and pasting code from docs. So I like those commands. What I like more is a single `make deps`. Anyway if you don't want to make those commands public we should make them private tasks: `make _controller-gen`. In this way it doesn't lists as task, auto-completion also doesn't offers it but we should execute it if we want. WDYT?

**Comment by Ricardo-Osorio** [comment]
That is the only reason I can think of for having it but honestly, I thought we all only ever run them "once in our lives" and thus there's no point in keeping them on the makefile
It's possible to argue it's useful for open source contributors or starters but in any of those cases the most likely scenario is that they already have those tools if they did any k8s dev work
Making them private beats the purpose of my intention, which is to reduce the size of the makefile. I use 3/4 rules at most

**Comment by mhmxs** [comment]
@Ricardo-Osorio `if they did any k8s dev work` and hopefully they have the same version of all the dependencies. Different projects are using different versions.

**Comment by mhmxs** [comment]
@Ricardo-Osorio Why not place them into a separated Makefile and include it in the main, so the main file size should be smaller and also we have the helpers.

**Comment by Ricardo-Osorio** [comment]
I reintroduced the dependencies part. I will try to keep the scope of the change smaller

**Review by mhmxs — APPROVED** [review]

**Review by mhmxs — APPROVED** [review]

**Pull request merged**
