### PR TITLE
Update api manager version to 1.2.4

### PR DESCRIPTION
**Pull request by Ricardo-Osorio**
Relies on #105 
With that change all we need to push is a change to the version string and the rest of the process should be taken care of by the newly introduced action

### CODE REVIEW

**Comment by Mojachieee** [comment]
This won't actually trigger the files to be generated, as the workflow doesn't run on push (or PR). 

The idea was to have an api-manager release trigger the action, which will then generate the files and create a PR

**Comment by mhmxs** [comment]
If i understand well the PR there must be an extra commit at the end, with upgraded manifests to 1.2.4?

**Comment by Ricardo-Osorio** [comment]
Miss understood, and I am too late for that then. I will generate it locally

**Comment by mhmxs** [comment]
@Ricardo-Osorio i think you have to rebase your branch, because we merged automation just now. (my bad i thought it is working)

**Comment by Ricardo-Osorio** [comment]
> @Ricardo-Osorio i think you have to rebase your branch, because we merged automation just now. (my bad i thought it is working) https://github.com/storageos/operator/pull/105/files

There we go :)

**Review by mhmxs — APPROVED** [review]

**Comment by nolancon** [comment]
Am I right in saying that this PR is now superseded by #109 ?

**Comment by Ricardo-Osorio** [comment]
Yes it seems that way, dropping this one

**Pull request closed without merging**
